# Generated by Django 4.2.6 on 2023-12-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='devise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
