# Generated by Django 4.2.6 on 2024-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndk_app', '0007_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='devise',
            field=models.CharField(blank=True, choices=[('euro', 'Є'), ('dollar', '$')], max_length=255, null=True),
        ),
    ]
