# Generated by Django 4.2.6 on 2024-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndk_app', '0011_etiquette_article_etiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
