# Generated by Django 4.2.6 on 2024-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndk_app', '0012_etiquette_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lien_paiement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
